[package]
name = "wind-coordinator"
version.workspace = true
edition.workspace = true

[dependencies]
wind-ipc = { path = "../wind-ipc" }
wind-bridge = { path = "../wind-bridge" }
wind-config = { path = "../wind-config" }
wind-store = { path = "../wind-store" }
wind-dict = { path = "../wind-dict" }
wind-engine = { path = "../wind-engine" }
wind-candidate = { path = "../wind-candidate" }
wind-transform = { path = "../wind-transform" }
wind-theme = { path = "../wind-theme" }
wind-ui = { path = "../wind-ui" }
wind-cmdbar = { path = "../wind-cmdbar" }
wind-phrase = { path = "../wind-phrase" }
wind-keys = { path = "../wind-keys" }
wind-quick-input = { path = "../wind-quick-input" }
wind-reverse = { path = "../wind-reverse" }
wind-punct = { path = "../wind-punct" }
tokio = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
chrono = "0.4"
open = "5"
serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }
fontdb = "0.22"

[target.'cfg(windows)'.dependencies]
windows = { workspace = true }

[dev-dependencies]
wind-config = { path = "../wind-config" }
wind-bridge = { path = "../wind-bridge" }
wind-ipc = { path = "../wind-ipc" }
