[package]
name = "wind_service"
version.workspace = true
edition.workspace = true

[[bin]]
name = "wind_input"
path = "src/main.rs"

[features]
default = []
debug_variant = ["wind-config/debug_variant"]

[dependencies]
wind-ipc = { path = "../../crates/wind-ipc" }
wind-coordinator = { path = "../../crates/wind-coordinator" }
wind-bridge = { path = "../../crates/wind-bridge" }
wind-config = { path = "../../crates/wind-config" }
wind-store = { path = "../../crates/wind-store" }
wind-dict = { path = "../../crates/wind-dict" }
wind-engine = { path = "../../crates/wind-engine" }
wind-ui = { path = "../../crates/wind-ui" }
wind-theme = { path = "../../crates/wind-theme" }
wind-webapi = { path = "../../crates/wind-webapi" }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-appender = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows = { workspace = true }
