[package]
name = "wind-bridge"
version.workspace = true
edition.workspace = true

[dependencies]
wind-ipc = { path = "../wind-ipc" }
tracing = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
bytes = "1"

[target.'cfg(windows)'.dependencies]
windows = { workspace = true }

[target.'cfg(unix)'.dependencies]
libc = "0.2"
